name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run tests
      run: go test -v -race ./...

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        CURRENT_TAG=${GITHUB_REF#refs/tags/}
        
        echo "Previous tag: $PREVIOUS_TAG"
        echo "Current tag: $CURRENT_TAG"
        
        # Generate changelog
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "This is the first release!" > changelog.md
          echo "" >> changelog.md
          git log --pretty=format:"- %s" >> changelog.md
        else
          echo "## What's Changed" > changelog.md
          echo "" >> changelog.md
          git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s" >> changelog.md
        fi
        
        echo "" >> changelog.md
        echo "" >> changelog.md
        echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...${CURRENT_TAG}" >> changelog.md
        
        # Set changelog as output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat changelog.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changelog.md
        generate_release_notes: false